# Generated by Django 4.2 on 2023-07-01 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emisiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField(max_length=100)),
                ('yacimiento', models.TextField(max_length=100)),
                ('area', models.TextField(max_length=100)),
                ('sistema', models.TextField(max_length=100)),
                ('ubicacion', models.CharField(max_length=200)),
                ('fuga', models.CharField(max_length=300)),
                ('fluido', models.TextField(max_length=100)),
                ('sustancia', models.TextField(max_length=100)),
                ('componente', models.TextField(max_length=100)),
                ('instalacion', models.TextField(max_length=100)),
                ('tamAccesorio', models.TextField(max_length=100)),
                ('medicion', models.PositiveIntegerField()),
                ('medicion15', models.TextField(max_length=100)),
                ('presion', models.TextField(max_length=100)),
                ('ciclado', models.TextField(max_length=50)),
                ('ignicion', models.TextField(max_length=50)),
                ('localizacion', models.TextField(max_length=50)),
                ('fechaReporte', models.DateField()),
                ('fechaActualizado', models.DateField()),
            ],
        ),
    ]
