# Generated by Django 4.2 on 2023-07-01 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisiones',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='ciclado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='componente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='fluido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='fuga',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='ignicion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='instalacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='localizacion',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='medicion15',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='presion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='sistema',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='site',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='sustancia',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='tamAccesorio',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='ubicacion',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='emisiones',
            name='yacimiento',
            field=models.CharField(max_length=100),
        ),
    ]
