# Generated by Django 4.2 on 2023-07-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emisiones', '0003_emisiones_operador'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Emisiones',
            new_name='Emision',
        ),
    ]
