# Generated by Django 4.2 on 2023-07-02 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emisiones', '0004_rename_emisiones_emision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emision',
            name='fechaActualizado',
        ),
        migrations.AddField(
            model_name='emision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='emision',
            name='updated_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='emision',
            name='operador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
