# Generated by Django 4.2 on 2023-07-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emisiones', '0005_remove_emision_fechaactualizado_emision_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emision',
            old_name='operador',
            new_name='usuario',
        ),
    ]
