# Generated by Django 4.2 on 2023-07-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisiones', '0006_rename_operador_emision_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='emision',
            name='emisionSuperada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emision',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='emision',
            name='site',
            field=models.CharField(choices=[('PISCO', 'Pisco'), ('MALVINAS', 'Malvinas')], default='Pisco', max_length=20),
        ),
        migrations.AlterField(
            model_name='emision',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='emision',
            name='yacimiento',
            field=models.CharField(choices=[('PROCESOS', 'Procesos'), ('SERVICIOS', 'Servicios')], default='Pisco', max_length=100),
        ),
    ]
