# Generated by Django 4.2 on 2023-07-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emisiones', '0008_emision_fcf_emision_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='emision',
            name='imagen',
            field=models.ImageField(null=True, upload_to='images_emisiones'),
        ),
    ]
